### ISSUE TITLE
Automatic open-needs-ls fails if current user has no sudo

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#41] opened 2022-02-23 21:13 UTC
I am not sure if this is a usecase to be handled, but this is something what happened to me.

I had an older version of open-needs-ls installed and the extension notified me of a newer version.
I had removed the "sudo" for current user for security reasons. The automatic uninstallation of needls failed because of the following permission issue.
>PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/needls/'

It seems to be possible to do a manual pip install of a newer version without sudo and the new version gets installed "locally".
Does it make sense to remove the uninstall step all together and do a new install only? Would this work for cases where sudo is not available?

**Comment by danwos** [comment] 2022-02-24 06:52
Mhh it all depends on the folder permission setup of the OS or docker container.

Removing the `pip uninstall ...` part could help, but I guess that `pip install` should be affected as well.
I'm not sure and have to make some tests.

**Comment by danwos** [comment] 2022-03-30 10:42
I close this as the issue is related to the general Python environment setup and its permission configuration must be right.

All we can do is detect problems and write meaningful error messages.
But I would not change the internal behavior.

**Comment by twodrops** [comment] 2022-04-21 02:57
Installing esbonio when rST Extension offers the pop works fine in the same environment. I guess it is worth looking at the difference in implementation.
https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/0386a90bedf1b1a9ec80172cdd443d8a01ae8836/src/util/python.ts#L246

If no noticeable difference in implementation is present, it would be nice to have an error message to use pip manually as done by rST extension.

**Comment by haiyangToAI** [comment] 2022-07-08 09:02
Hi,

This project is not maintained anymore and is archived.

All the current features have been moved to project Sphinx-Needs: https://github.com/useblocks/sphinxcontrib-needs/tree/master/sphinx_needs/lsp. The features will be automatically detected by VsCode extension reStructuredText: https://github.com/vscode-restructuredtext/vscode-restructuredtext in your Sphinx-Needs project.

Further features development will be done inside the Sphinx-Needs project.

Thanks.

**Closed by haiyangToAI** 2022-07-08 09:02 UTC
