### ISSUE TITLE
Start and automatic installation of needls fails

### ISSUE THREAD

**Issue by r-o-b-e-r-t-o** [open-needs/open-needs-ide#14] opened 2022-01-20 11:02 UTC
I tried to install the extension and hit the 'Yes' option in the dialog that notifies about missing needls.
The installation fails.
Pip uninstall command fails (see below).
After manual install of needls still the extension doesn't start.
It seems the version check is failing because needls does not contain `__version__` dunder.

Here is the output of my vscode console:

```
Running cmd: /mnt/c/git/colibry/.lvenv/bin/python /mnt/c/git/colibry/.lvenv/bin/python -c "import needls; print(needls.__version__)"
Error
Command failed: /mnt/c/git/colibry/.lvenv/bin/python -c "import needls; print(needls.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'needls' has no attribute '__version__'

Error: Command failed: /mnt/c/git/colibry/.lvenv/bin/python -c "import needls; print(needls.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'needls' has no attribute '__version__'

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'needls' has no attribute '__version__'

Running cmd: /mnt/c/git/colibry/.lvenv/bin/python /mnt/c/git/colibry/.lvenv/bin/python -m pip install pip --upgrade
Successful exec
Running cmd: /mnt/c/git/colibry/.lvenv/bin/python /mnt/c/git/colibry/.lvenv/bin/python -m pip uninstall "git+https://github.com/open-needs/open-needs-ide" -y
Error
Command failed: /mnt/c/git/colibry/.lvenv/bin/python -m pip uninstall "git+https://github.com/open-needs/open-needs-ide" -y
WARNING: Invalid requirement: 'git+https://github.com/open-needs/open-needs-ide' ignored - the uninstall command expects named requirements.
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")

Error: Command failed: /mnt/c/git/colibry/.lvenv/bin/python -m pip uninstall "git+https://github.com/open-needs/open-needs-ide" -y
WARNING: Invalid requirement: 'git+https://github.com/open-needs/open-needs-ide' ignored - the uninstall command expects named requirements.
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

WARNING: Invalid requirement: 'git+https://github.com/open-needs/open-needs-ide' ignored - the uninstall command expects named requirements.
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")
```

OS: WSL/Ubuntu 20.04 on Windows 10
VScode version: 1.63.2

**Comment by twodrops** [comment] 2022-01-20 11:23
@r-o-b-e-r-t-o I feel this is related to the issues I raised yesterday
See 
https://github.com/open-needs/open-needs-ide/issues/11
https://github.com/open-needs/open-needs-ide/issues/12

They are fixed but not yet released to Marketplace and PyPi according to @danwos

**Comment by danwos** [comment] 2022-01-20 12:20
I have just released a new version of the VS Code extension (0.0.11).
This checks, if the installed needls server has version 0.0.11 as well. If not it tries to install it from gtihub repo.

I think it should contain the needed fixes for the above problem.

**Comment by danwos** [comment] 2022-01-20 15:47
Argh thanks for testing.
It's not so easy to automate all the possible setups.

But does this even happen when the latest needls is manually installed?

**Comment by kapinnow** [comment] 2022-01-21 07:01
For automating the test, I still try to get https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions# running. Probably there is a local issue at my side. Could you potentially check on yours?

**Comment by r-o-b-e-r-t-o** [comment] 2022-01-21 08:40
> But does this even happen when the latest needls is manually installed?

Works like charm with manual install.

**Comment by danwos** [comment] 2022-01-21 12:09
Ok, worked on the Installation routine and released a new version: 0.0.12.
If this gets installed, it will also ask you to reinstall needls, as you have an old version (0.0.11).

The project also has now some automated test-env setups, so that I'm able to run certain tests with predefined env-configuration quite fast. 
I hope this issue is fixed now :) 
@r-o-b-e-r-t-o : Can you please check, if you have some time.

**Comment by kapinnow** [comment] 2022-01-21 13:51
Checked it and "works for me". Great work, Daniel (including making it available in the marketplace). Nice.
The only thing, that I typically need to do is to change the Docs Root and Build Path as expected.

**Comment by danwos** [comment] 2022-01-24 13:06
I close this issue, as with the current release (0.0.13), the installation part should be stable, as it is based now completely on releases from PyPi and VS Code marketplace.

**Closed by danwos** 2022-01-24 13:06 UTC

**Comment by twodrops** [comment] 2022-01-24 13:48
I can confirm that if needls is installed from PyPi
`pip install open-needs-ls`
it works correctly with 0.0.13

Also with no needls installed, the pop installs it correctly.

![2022-01-24_14h46_37](https://user-images.githubusercontent.com/103930/150794404-b748c065-526e-4bf6-aaea-5806c29821fd.png)
